# GitHub CI/CD version

name: 'Embedded CI/CD'

on:
  pull_request:
  push:
    branches:
    - main
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      -
        name: Create Docker Cache Folder
        run: mkdir -p /tmp/docker
      -
        name: Restore Docker Image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/.Dockerfile') }}
      -
        name: Build Docker Embedded CI/CD Image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: caio_guimaraes/cicd-dev:latest 
          outputs: type=docker,dest=/tmp/docker/${{ runner.os }}-image.tar